### ISSUE TITLE
`Match::AnyRange`

### ISSUE THREAD

**Issue by Iron-E** [Iron-E/clinvoice#6]
Allow users to specify multiple ranges when querying.

**Comment by Iron-E** [comment]
This is not needed, as the following is equivalent:

```yaml
---
condition: Or
value:
  - condition: InRange
    value:
      - # date range begin
      - # date range end
  - condition: InRange
    value:
      - # date range begin
      - # date range end
  # ... so on
```
